<html>
	<head>
		<title>Alumni Business Directory</title>
	</head>

	<body>
		<?php
		echo "The content of these web pages is not generated by and does not represent the views of Santa Clara University or any of its departments or organizations.";
        header('Location: students.engr.scu.edu/~jday/php/Alumni-Business-Directory-System/login.php');
		?>
	</body>
</html>



