<!doctype html>
<!--The content of these web pages is not generated by and does not represent the views of Santa Clara University or any of its departments or organizations.-->
<html>
<head>
	<link href="../css/styles.css" rel="stylesheet" type="text/css"/>
	<meta charset="UTF-8">
	<meta name="viewport" content="width=device-width, initial-scale=1">
	<link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.1.3/css/bootstrap.min.css" integrity="sha384-MCw98/SFnGE8fJT3GXwEOngsV7Zt27NXFoaoApmYm81iuXoPkFOJwJ8ERdknLPMO" crossorigin="anonymous">
	<script src="https://code.jquery.com/jquery-3.2.1.slim.min.js" integrity="sha384-KJ3o2DKtIkvYIK3UENzmM7KCkRr/rE9/Qpg6aAZGJwFDMVNA/GpGFF93hXpG5KkN" crossorigin="anonymous"></script>
	<script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.12.9/umd/popper.min.js" integrity="sha384-ApNbgh9B+Y1QKtv3Rn7W3mgPxhU9K/ScQsAP7hUibX39j7fakFPskvXusvfa0b4Q" crossorigin="anonymous"></script>
	<script src="https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0/js/bootstrap.min.js" integrity="sha384-JZR6Spejh4U02d8jOt6vLEHfe/JQGiRRSQQxSfFWpi1MquVdAyjUar5+76PVCmYl" crossorigin="anonymous"></script>
	<title>Alumni Business Directory</title>
</head>

<body>
	<div class="jumbotron">
		<h1>Santa Clara University Business Directory</h1>
	</div>

    <?php
    ini_set('session.gc.maxlifetime', 3600);    // server keeps session data for at least 1 hour
    session_set_cookie_params(3600);            // clients remember their session id for 1 hour
    session_start();
    session_regenerate_id(true);

    require_once "../src/login.php";
    require_once "../src/user.php";

    $user = new User();
    $login_error = "";

    // When user clicks Submit button
    if (isset($_POST["submit"])) {
        try {
            $_SESSION['login'] = login($_POST["email"], $_POST["password"]);

            if ($_SESSION['login']) {
                $json = $user->get_one("email", $_POST["email"]);
                $json_obj = json_decode($json);

                // Track user email, role and ID
                $_SESSION['email'] = $json_obj[0]->email;
                $_SESSION['role'] = $json_obj[0]->role;
                $_SESSION['user'] = $json_obj[0]->id;

                // Redirect to home page based on user's role
                $loc = ($_SESSION['role'] == "Manager") ? "manager_home.php" : "user_home.php";
                header("Location:" . $loc);
            } else {
                $login_error = "Invalid Email or Password";
            }
        } catch(Exception $e) {
            echo $e . "<br>";
        }
    }
    ?>

	<form class="container col-lg-5 col-sm-10" method="post" action="login.php">
  	<div class="form-group">
    	<label for="exampleInputEmail1">Email</label>
    	<input type="email" name="email" class="form-control" id="exampleInputEmail1" aria-describedby="emailHelp" placeholder="Enter email" required>
  	</div>
  	<div class="form-group">
    	<label for="exampleInputPassword1">Password</label>
    	<input type="password" name="password" class="form-control" id="exampleInputPassword1" placeholder="Enter password" required>
  	</div>
	<div class="form-group">
		<a href="signup.php">Don't have an account?</a>
	</div>
  	<input type="submit" name="submit" class="btn submitbtn">
    <?php echo "<br>" . $login_error; ?>
	</form>
</body>
</html>
